### ISSUE TITLE
Cannot insert table to editor

### ISSUE THREAD

**Issue by eeezae** [Saul-Mirone/milkdown#658]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.3.2

### Link to runnable example

https://codesandbox.io/s/busy-feistel-3q3esq

### Steps to reproduce

Click menu table btn to insert a table

### Expected behavior

Insert a table in editor

### Actual behavior

Error occurs.
```
index.ts:13 Uncaught MilkdownError: Context "InsertTable" not found, do you forget to inject it?
    at u (index.ts:13:5)
    at Object.getSlice (container.ts:20:19)
    at tt2.get (commands.ts:40:32)
    at tt2.call (commands.ts:53:26)
    at HTMLButtonElement.<anonymous> (button.ts:84:30)
u @ index.ts:13
getSlice @ container.ts:20
get @ commands.ts:40
call @ commands.ts:53
(anonymous) @ button.ts:84
```

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by eeezae** [comment]
use gfm instead of conmmonmark
