### ISSUE TITLE
[Bug] There is a bug in using tooltip in vite

### ISSUE THREAD

**Issue by yuyuko233** [Saul-Mirone/milkdown#733]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"@milkdown/plugin-tooltip": "^6.4.1"

### Steps to reproduce

Exception:
```

X [ERROR] No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "Env"
                                                                                              
    node_modules/@milkdown/plugin-tooltip/node_modules/@milkdown/utils/lib/index.es.js:1:441: 
      1 │ ...imerCtx as Tt, themeManagerCtx as Y, emotionCtx as St, createSlice as f, createContainer as jt, createClock as Rt, Env as Ot, editorViewCtx as C, serializerCtx as At, parserCtx as gt, editorStateOptionsCtx as Et } from "@milkdown/core"; 
        ╵                                                                                                                       ~~~

21:26:49 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@milkdown/plugin-tooltip/node_modules/@milkdown/utils/lib/index.es.js:1:441: ERROR: No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "Env"
    at failureErrorWithLog (D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:1624:15)
    at D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:1266:28
    at runOnEndCallbacks (D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:1046:63)
    at buildResponseToResult (D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:1264:7)
    at D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:1377:14
    at D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (D:\JetBrains\Project\html\ts-test\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
Vite Error, /node_modules/.vite/deps/@milkdown_core.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_theme-nord.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_preset-commonmark.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_plugin-emoji.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_plugin-tooltip.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_core.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_theme-nord.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_preset-commonmark.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_plugin-emoji.js?v=5c414689 optimized info should be defined
Vite Error, /node_modules/.vite/deps/@milkdown_plugin-tooltip.js?v=5c414689 optimized info should be defined

```

Code: 
```typescript
import {defaultValueCtx, Editor, rootCtx} from '@milkdown/core';
import { nord } from '@milkdown/theme-nord';
import { commonmark } from '@milkdown/preset-commonmark';
import { emoji } from "@milkdown/plugin-emoji";
import { tooltip } from '@milkdown/plugin-tooltip';

let milkdownCtx: Editor
let text = '# Hello Milkdown!'

Editor.make().config((ctx) => {
    ctx.set(rootCtx, document.querySelector('#MarkdownEditor'))
    ctx.set(defaultValueCtx, text)
}).use(commonmark)
    .use(nord)
    .use(emoji)
    .use(tooltip)
    .create()
    .then(r => milkdownCtx = r)
    .catch(err => {
        console.error(err)
    })

```

### Expected behavior

Start and use normally.

### Actual behavior

Exception

### Runtime

Chrome, Firefox

### OS

Windows

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Can't reproduce on my side, maybe you can try remove node_modules and reinstall.

**Comment by yuyuko233** [comment]
> Can't reproduce on my side, maybe you can try remove node_modules and reinstall.

The same result.
```
D:\Env\node\npm.cmd run dev
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> milkdown-editor@0.0.0 dev
> vite


  VITE v3.1.3  ready in 762 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
X [ERROR] No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "Env"

    node_modules/@milkdown/plugin-menu/node_modules/@milkdown/utils/lib/index.es.js:1:441:
      1 │ ...imerCtx as Tt, themeManagerCtx as Y, emotionCtx as St, createSlice as f, createContainer as jt, createClock as Rt, Env as Ot, editorViewCtx as C, serializerCtx as At, parserCtx as gt, editorStateOptionsCtx as Et } from "@milkdown/core";
        ╵                                                                                                                       ~~~

X [ERROR] No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "rootDOMCtx"

    node_modules/@milkdown/plugin-menu/lib/index.es.js:1:215:
      1 │ ...ey as I, getPalette as A, ThemeIcon as T, commandsCtx as L, ThemeSize as f, ThemeColor as x, ThemeBorder as y, ThemeShadow as _, rootCtx as M, ThemeScrollbar as $, ThemeFont as H, createCmd as P, rootDOMCtx as v } from "@milkdown/core"; 
        ╵                                                                                                                                                                                                        ~~~~~~~~~~

D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:1566
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
node_modules/@milkdown/plugin-menu/lib/index.es.js:1:215: ERROR: No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "rootDOMCtx"
node_modules/@milkdown/plugin-menu/node_modules/@milkdown/utils/lib/index.es.js:1:441: ERROR: No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "Env"
    at failureErrorWithLog (D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:1566:15)
    at D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:1022:7)
    at D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (D:\JetBrains\Project\html\milkdown-editor\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 215,
        file: 'node_modules/@milkdown/plugin-menu/lib/index.es.js',
        length: 10,
        line: 1,
        lineText: 'import { createCmdKey as I, getPalette as A, ThemeIcon as T, commandsCtx as L, ThemeSize as f, ThemeColor as x, ThemeBorder as y, ThemeShadow as _, rootCtx as M, ThemeScrollbar as $, ThemeFont as H, createCmd as P, rootDOMCtx as v 
} from "@milkdown/core";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "rootDOMCtx"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 441,
        file: 'node_modules/@milkdown/plugin-menu/node_modules/@milkdown/utils/lib/index.es.js',
        length: 3,
        line: 1,
        lineText: 'import { createTimer as vt, SchemaReady as p, commandsCtx as S, commandsTimerCtx as Ct, inputRulesCtx as q, editorStateTimerCtx as B, ThemeReady as $, marksCtx as D, schemaCtx as j, schemaTimerCtx as G, nodesCtx as H, prosePluginsC
tx as R, InitReady as J, remarkPluginsCtx as Q, nodeViewCtx as W, markViewCtx as X, editorViewTimerCtx as Tt, themeManagerCtx as Y, emotionCtx as St, createSlice as f, createContainer as jt, createClock as Rt, Env as Ot, editorViewCtx as C, serialize
rCtx as At, parserCtx as gt, editorStateOptionsCtx as Et } from "@milkdown/core";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/@milkdown/core/lib/index.es.js" for import "Env"'
    }
  ],
  warnings: []
}

Process finished with exit code 1
```

**Comment by Saul-Mirone** [comment]
https://stackblitz.com/edit/vitejs-vite-gzw1kk?file=src/components/Milkdown.vue

I can't reproduce, please check your node_modules and lock files.
